"use client";

import type React from "react";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

interface DisclaimerModalProps {
  onAgree: () => void;
}

export function DisclaimerModal({ onAgree }: DisclaimerModalProps) {
  const [isOpen, setIsOpen] = useState(true);
  const [scrolledToBottom, setScrolledToBottom] = useState(false);

  const disclaimerText = `Welcome to project Vivek, and thank you for taking out the time to try this. Before you proceed, you must read and acknowledge the following:

• Project, Not a Product: This is a personal, non-commercial, and experimental project created for demonstration and learning purposes. It is not a commercial product and should not be treated as a definitive, authoritative, or professional service.

• Source Material: All information provided by this application is derived exclusively from the following public domain text- The link to which is provided at the end of this section

THE GARUDA PURÂṆA (SÂRODDHÂRA) WITH ENGLISH TRANSLATION By: Ernest Wood & S.V. Subrahmanyam Publisher: Pâṇiṇi Office, Allahabad [1911] E-book Source: PDF by Ganesh Rama Kumar

• No Guarantee of Accuracy: The source material is a historical English translation from 1911. As with all translations of ancient texts, interpretations may vary, and the accuracy or completeness of this specific translation is not guaranteed. I (the creator of this project) am not the author of this text and am not responsible for its content or correctness.

• AI & Reliability: The responses are generated by a Large Language Model (LLM) based on the source text. The AI may misinterpret the text, hallucinate, omit information, or present content out of context. Do not use this application as a substitute for academic, theological, or professional advice, if done so - it is understood that the user has read this and will hold the full responsibility to the results

• Sensitive Content & Sentiments: The Garuda Purana is an ancient religious text. Its content reflects historical and cultural contexts that include descriptions of acts, karmic consequences, and societal norms that may be graphic, sensitive, or conflict with modern values. This application is not intended to offend, harm, or hurt the sentiments of any individual, religion, or group. The content is presented as-is from the source text for informational exploration only.

•Use At Your Own Risk: You are using this application entirely at your own risk. The creator of this project shall not be liable for any damages, distress, or misunderstanding (personal, cultural, religious, or otherwise) that may arise from your use or interpretation of the information provided.

By clicking "Accept" or continuing to use this application, you acknowledge that you have read, understood, and agreed to these terms.`;

  const handleScroll = (e: React.UIEvent<HTMLDivElement>) => {
    const element = e.currentTarget;
    const isAtBottom =
      element.scrollHeight - element.scrollTop < element.clientHeight + 50;
    setScrolledToBottom(isAtBottom);
  };

  const handleAgree = () => {
    localStorage.setItem("disclaimer_agreed", "true");
    setIsOpen(false);
    onAgree();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4 animate-in-fade">
      <Card className="w-full max-w-2xl max-h-[80vh] overflow-hidden flex flex-col shadow-2xl animate-in-up">
        {/* Header */}
        <div className="bg-gradient-to-r from-primary/10 to-accent/10 border-b border-border p-6">
          <h2 className="text-2xl font-bold text-foreground">
            Disclaimer - And a few pointers
          </h2>
          <p className="text-sm text-muted-foreground mt-1">
            Please read before proceeding
          </p>
        </div>

        {/* Scrollable content */}
        <div
          className="flex-1 overflow-y-auto p-6 scrollbar-hide scroll-smooth"
          onScroll={handleScroll}
        >
          <div className="prose prose-sm dark:prose-invert max-w-none">
            {disclaimerText.split("\n\n").map((paragraph, idx) => (
              <p
                key={idx}
                className="text-sm leading-relaxed text-foreground/90 mb-4 whitespace-pre-wrap"
              >
                {paragraph}
              </p>
            ))}

            {/* Sources Section */}
            <div className="mt-8 pt-6 border-t border-border">
              <h3 className="text-lg font-semibold text-foreground mb-4 flex items-center gap-2">
                <svg
                  className="w-5 h-5 text-primary"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"
                  />
                </svg>
                Sources & References
              </h3>

              <div className="space-y-3">
                {/* Source Text Link */}
                <a
                  href="https://lakshminarayanlenasia.com/downloads/GarudaPurana.pdf"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-3 p-4 rounded-lg border border-border hover:border-primary/50 hover:bg-primary/5 transition-all group"
                >
                  <div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center group-hover:bg-primary/20 transition-colors">
                    <svg
                      className="w-5 h-5 text-primary"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
                      />
                    </svg>
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-foreground group-hover:text-primary transition-colors">
                      Garuda Purana (PDF)
                    </p>
                    <p className="text-xs text-muted-foreground">
                      Original source text used for this project
                    </p>
                  </div>
                  <svg
                    className="w-5 h-5 text-muted-foreground group-hover:text-primary transition-colors"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"
                    />
                  </svg>
                </a>

                {/* Source Provider Link */}
                <a
                  href="https://lakshminarayanlenasia.com/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-3 p-4 rounded-lg border border-border hover:border-primary/50 hover:bg-primary/5 transition-all group"
                >
                  <div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center group-hover:bg-primary/20 transition-colors">
                    <svg
                      className="w-5 h-5 text-primary"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9"
                      />
                    </svg>
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-foreground group-hover:text-primary transition-colors">
                      Lakshmi Narayan Lenasia Temple
                    </p>
                    <p className="text-xs text-muted-foreground">
                      Source provider and spiritual resource center
                    </p>
                  </div>
                  <svg
                    className="w-5 h-5 text-muted-foreground group-hover:text-primary transition-colors"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"
                    />
                  </svg>
                </a>
              </div>
            </div>
          </div>
        </div>

        {/* Footer with action buttons */}
        <div className="border-t border-border p-6 bg-card flex gap-3 justify-end items-center">
          {!scrolledToBottom && (
            <p className="text-xs text-muted-foreground mr-auto">
              Scroll down to agree
            </p>
          )}
          <Button
            onClick={handleAgree}
            disabled={!scrolledToBottom}
            className="bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            I Agree & Continue
          </Button>
        </div>
      </Card>
    </div>
  );
}
